DATASET: genre_dortmund

DATA_FOLDER: /home/pablo/reps/mtgdb-models/src/musicnn_training/data/genre_dortmund/
MODEL_FOLDER: /home/pablo/reps/mtgdb-models/src/musicnn_training/exp/vgg/genre_dortmund/

config_preprocess:
  msd_spec:
    audio_folder: /home/jpons/audio/msd/
    hop: 256
    identifier: msd
    index_file: index/msd/index_msd.tsv
    machine_i: 0
    n_fft: 512
    n_machines: 1
    n_mels: 96
    num_processing_units: 20
    resample_sr: 16000
    spectrogram_type: mel
    type: time-freq
  mtt_spec:
    audio_folder: /home/jpons/audio/mtt/
    hop: 256
    identifier: mtt
    index_file: index/mtt/index_mtt.tsv
    machine_i: 0
    n_fft: 512
    n_machines: 1
    n_mels: 96
    num_processing_units: 20
    resample_sr: 16000
    spectrogram_type: mel
    type: time-freq
  mtgdb_spec:
    audio_folder: /mnt/mtgdb-audio/stable/genre_dortmund/audio/wav/
    hop: 256
    identifier: genre_dortmund
    index_audio_file: index_audio.tsv
    index_repr_file: index_repr.tsv
    machine_i: 0
    n_fft: 512
    n_machines: 1
    n_mels: 96
    num_processing_units: 20
    resample_sr: 16000
    spectrogram_type: mel
    type: time-freq

config_train:
  spec:
    audio_representation_folder: /home/pablo/reps/mtgdb-models/src/musicnn_training/data/genre_dortmund/genre_dortmund__time-freq/
    batch_size: 32
    epochs: 150
    gt_train: /home/pablo/reps/mtgdb-models/src/musicnn_training/data/genre_dortmund/gt_train_0.csv
    gt_val: /home/pablo/reps/mtgdb-models/src/musicnn_training/data/genre_dortmund/gt_val_0.csv
    gt_test: /home/pablo/reps/mtgdb-models/src/musicnn_training/data/genre_dortmund/gt_test_0.csv
    index_repr_regularize: ''  # index with samples to use for regularization (unsupervised domain adaptation) 
    learning_rate: 0.001
    load_model: 
    model_number: 11
    n_frames: 187
    name_run: ''
    num_classes_dataset: 9
    optimizer: Adam
    pad_short: repeat-pad
    param_train_sampling: 1
    patience: 75
    pre_processing: logC
    train_sampling: random
    val_batch_size: 32
    weight_decay: 1.0e-05
    n_folds: 5
    fold: 0
    seed: 6
    mode : regular  # regular, adversarial_type_a, adversarial_type_b
    lambda: 0  # lambda for reversal gradient models
    discriminator_dimensions: 1
    discriminator_target: dataset
    coupling_layer_units : 100  # units of the first layer after the TL embeddings. 0 to omit a coupling layer
    task : labels  # labels, lowlevel_descriptors
    lowlevel_descriptor : loudness
